In [1]:
import numpy as np

In [2]:
np.random.rand(4,4)

array([[ 0.50790049,  0.21470588,  0.80301708,  0.07360804],
       [ 0.43182126,  0.79981498,  0.27304347,  0.70573063],
       [ 0.50169313,  0.00832502,  0.68778508,  0.45543259],
       [ 0.21928724,  0.0117709 ,  0.26365121,  0.15226263]])

In [3]:
randMat = np.mat(np.random.rand(4,4))
randMat.I

matrix([[  3.81571693e+00,  -2.66546089e+00,  -5.40887558e-01,
          -1.05851111e-02],
        [  1.87875064e+01,  -2.07910506e+01,  -4.49538766e-01,
           6.89934053e+00],
        [ -4.10965000e+00,   4.11496465e+00,  -9.41428041e-02,
           3.31629512e-02],
        [ -2.73853775e+01,   2.99930375e+01,   2.47576914e+00,
          -1.03023829e+01]])

In [4]:
invRandMat = randMat.I
randMat * invRandMat

matrix([[  1.00000000e+00,  -1.77635684e-15,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          -8.88178420e-16],
        [  0.00000000e+00,   0.00000000e+00,   5.55111512e-17,
           1.00000000e+00]])

In [5]:
myEye = randMat*invRandMat
myEye - np.eye(4)

matrix([[  1.77635684e-15,  -1.77635684e-15,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          -8.88178420e-16],
        [  0.00000000e+00,   0.00000000e+00,   5.55111512e-17,
           0.00000000e+00]])