In [25]:
import numpy as np
import operator

In [4]:
group = np.array([[1.0, 1.1], [1.0, 1.0], [0,0], [0, 0.1]])
labels = ['A','A','B','B']



In [5]:
inX = [0, 0]
dataSet = group
k = 3

In [8]:
# 训练样本数目
dataSet.shape[0]

4

In [10]:
dataSetSize = dataSet.shape[0]
np.tile(inX, (dataSetSize, 1)) 

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [11]:
# 最终要预测的向量只有1组，但训练样本数有4组，所以把预测的向量复制为4组，然后就是矩阵减法
# 计算每一组中的距离
diffMat = np.tile(inX, (dataSetSize, 1)) - dataSet
diffMat

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -0.1]])

In [12]:
sqDiffMat = diffMat ** 2
sqDiffMat

array([[ 1.  ,  1.21],
       [ 1.  ,  1.  ],
       [ 0.  ,  0.  ],
       [ 0.  ,  0.01]])

In [17]:
# 不设定axis参数，就是矩阵内所有元素简单相加
sqDiffMat.sum()

4.2199999999999998

In [19]:
# axis参数不可以大于等于ndim数（维度数），这里不可以大于等于2
sqDistances = sqDiffMat.sum(axis=1)
# 计算两个向量点之间的欧氏距离
distances = sqDistances ** 0.5
distances

array([ 1.48660687,  1.41421356,  0.        ,  0.1       ])

In [21]:
# 把数组从小到大排列（返回的是元素中的索引号/序列号）
# 0：1.48660687
# 1：1.41421356
# 2：0
# 3：0.1
# 所以结果是[2,3,1,0]
sortedDistIndicies = distances.argsort()
sortedDistIndicies

array([2, 3, 1, 0])

In [22]:
classCount = {}

# 选择距离最小的k个点，确定这些元素所在的主要分类：
# classCount字典，key就是分类，value就是出现此分类的次数
for i in range(k):
    voteIlabel = labels[sortedDistIndicies[i]]
    classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
classCount

{'A': 1, 'B': 2}

In [29]:
items = classCount.items()
items

dict_items([('B', 2), ('A', 1)])

In [26]:
# 排序
# 将classCount字典分解为元组列表，然后使用itemgetter方法，按照第二个元素的次序（？）对元组进行排序
# 此处的排序为逆序，即按照从最大到最小次序排序，最后返回发生频率最高的元素标签
sortedClassCount = sorted(items,
                   key=operator.itemgetter(1), reverse=True)
sortedClassCount


[('B', 2), ('A', 1)]

In [27]:
sortedClassCount[0]

('B', 2)

In [28]:
# 这个就是最终结果
sortedClassCount[0][0]

'B'