我理解就是数组内的元素复制

In [1]:
import numpy as np


In [2]:
a = np.array([0,1,2])
a

array([0, 1, 2])

In [3]:
np.tile(a, [0, 2])

array([], shape=(0, 6), dtype=int64)

In [4]:
np.tile(a, [1, 2, 3])

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2]]])

In [5]:
np.tile(a, [1, 2])

array([[0, 1, 2, 0, 1, 2]])

In [6]:
np.tile(a, [2, 1])

array([[0, 1, 2],
       [0, 1, 2]])

In [7]:
np.tile(a, [2,3,4])

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]])

In [8]:
np.tile(a, [2,3,4]).shape

(2, 3, 12)

In [10]:
b = np.array([[0],[1],[2]])
b.shape

(3, 1)

In [12]:
np.tile(b, (1,2))

array([[0, 0],
       [1, 1],
       [2, 2]])

In [13]:
np.tile(b, (2,1))

array([[0],
       [1],
       [2],
       [0],
       [1],
       [2]])