In [1]:
import numpy as np

# ndarray 与 Matrix

np.array 可以是任意维的数组  
np.mat 一定是二维的数组

例子：创建一个一维数组，数组有3个元素，每个元素都是1

In [51]:
arr_1 = np.ones(3)
arr_1

array([ 1.,  1.,  1.])

In [52]:
np.array(arr_1)

array([ 1.,  1.,  1.])

把这个一维数组转化为矩阵/二维数组

In [53]:
mat_1 = np.mat(arr_1)
mat_1

matrix([[ 1.,  1.,  1.]])

这个由一维数组转换而来的矩阵/二维数组, 列数为原来的元素个数

In [55]:
mat_1.shape

(1, 3)

数组相乘时，默认是对应元素的乘积(点乘)，要求两个数组的shape完全相等

In [68]:
arr__1_3 = np.ones((1,3))
arr___1_3 = np.ones((1,3))

arr__1_3 = arr__1_3 *2
arr___1_3 = arr___1_3 * 3
arr__1_3*arr___1_3

array([[ 6.,  6.,  6.]])

如果shape不相等，则会进行广播处理  
暂时是理解不能，只能尽量不要去进行shape不相等的数组乘法